const express = require("express");
const cors = require("cors");
const fs = require("fs");
const path = require("path");
const multer = require("multer");
const { exec } = require("child_process");

const app = express();
const PORT = 5000;

app.use(cors());
app.use(express.json());

// ---- STATIC FILES ----
app.use("/static", express.static(path.join(__dirname, "public")));

// ---- PATHS ----
const competitionsPath = path.join(__dirname, "data", "competitions.json");
const teamsPath = path.join(__dirname, "data", "teams.json");
const compStatsPath = path.join(__dirname, "data", "competition_stats.json");
const playersPath = path.join(__dirname, "data", "players.json");

// ---- LOAD DATA ----
let competitions = JSON.parse(fs.readFileSync(competitionsPath, "utf8"));
let teams = JSON.parse(fs.readFileSync(teamsPath, "utf8"));
let competitionStats = JSON.parse(fs.readFileSync(compStatsPath, "utf8"));

// ---- FILE UPLOAD ----
const upload = multer({ dest: "uploads/" });

// ---- ROUTES ----
app.get("/competitions", (req, res) => res.json(competitions));

app.get("/competitions/:id", (req, res) => {
  const id = parseInt(req.params.id);
  const competition = competitions.find((c) => c.id === id);
  competition
    ? res.json(competition)
    : res.status(404).json({ message: "Competition not found" });
});

app.get("/competitions/:id/teams", (req, res) => {
  const competitionId = parseInt(req.params.id);
  const filteredTeams = teams.filter((t) =>
    t.competitionIds.includes(competitionId)
  );
  res.json(filteredTeams);
});

app.get("/competitions/:id/stats", (req, res) => {
  const id = req.params.id;
  const stats = competitionStats[id];
  stats
    ? res.json(stats)
    : res.status(404).json({ message: "Stats not found for this competition" });
});

app.get("/teams", (req, res) => res.json(teams));

app.get("/teams/:id", (req, res) => {
  const id = parseInt(req.params.id);
  const team = teams.find((t) => t.id === id);
  team
    ? res.json(team)
    : res.status(404).json({ message: "Team not found" });
});

app.get("/teams/:id/players", (req, res) => {
  const teamId = parseInt(req.params.id);
  const players = JSON.parse(fs.readFileSync(playersPath, "utf8"));
  const teamPlayers = players.filter((p) => p.teamId === teamId);
  res.json(teamPlayers);
});

// ---- VIDEO ANALYSIS ENDPOINT ----
app.post("/api/analyze", upload.single("file"), (req, res) => {
  const inputPath = path.resolve(req.file.path);
  const cvScript = path.resolve(__dirname, "../cv-backend/main.py");
  const outputPath = path.resolve(__dirname, "../cv-backend/output/output.mp4");
  const finalPath = path.join(__dirname, "public", "output.mp4");

  console.log("Running analysis...");
  console.log("Python script:", cvScript);
  console.log("Input video:", inputPath);

  // Ensure public folder exists
  const publicDir = path.join(__dirname, "public");
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir);
  }

  exec(`python "${cvScript}" --video "${inputPath}"`, (error, stdout, stderr) => {
    console.log("STDOUT:", stdout);
    console.log("STDERR:", stderr);

    if (error) {
      console.error("Error running analysis:", error);
      return res.status(500).send("Analysis failed, see server logs.");
    }

    // Ensure Python produced the file
    if (!fs.existsSync(outputPath)) {
      console.error("Output file not found:", outputPath);
      return res.status(500).send("Output file not generated by Python script");
    }

    fs.copyFile(outputPath, finalPath, (err) => {
      if (err) {
        console.error("Error copying file:", err);
        return res.status(500).send("Error preparing output video");
      }
      res.json({ url: `http://localhost:${PORT}/static/output.mp4` });
    });
  });
});

// ---- START SERVER ----
app.listen(PORT, () =>
  console.log(`Server running on http://localhost:${PORT}`)
);
